name: atera_shared
description: Atera shared library
version: 1.0.0

environment:
    sdk: ^3.1.5

dependencies:
    intl: ^0.19.0
    latlong2: ^0.9.0
    omnimodel: ^1.1.8
    path: ^1.9.0
    point_in_polygon: ^1.0.0
    quiver: ^3.2.1
    vector_math: ^2.1.4

dev_dependencies:
    lints: ^3.0.0

dependency_overrides:
    path: 1.8.3
